# Copyright 2019-2020 The Khronos Group Inc.
# SPDX-License-Identifier: Apache-2.0

# CI build script for Travis.
# See https://docs.travis-ci.com/user/multi-os/ for more info.

branches:
  except:
  - ktxsw

language:
  - cpp

matrix:
  include:
    # works on Focal
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-7
            - g++-7
      dist: focal
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      compiler: gcc # clang is tested by macOS build
      sudo: required
    - os: osx
      compiler: clang
      osx_image: xcode11.4
    - os: windows

# Phase 1: Git clone - done automatically.
# Phase 2: Install apt addons.
# Phase 3: Install cache components - Currently not using a cache
# then the following phases:
before_install:

install:
- |
  case $TRAVIS_OS_NAME in
    linux)
      # No need to install git-lfs. It is part of Travis's Ubuntu environment.
      sudo apt-get -qq update &&
      sudo apt-get -qq install doxygen
      ;;
    osx)
      brew install doxygen
      ;;
    windows)
      choco install -y doxygen.install
      ;;
  esac

before_script:

script:
- |
  case $TRAVIS_OS_NAME in
  linux)
    cmake -H. -B _build -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=install -DBUILD_TESTS=ON -DBUILD_DOCS=ON -DCMAKE_BUILD_TYPE=Release
    cmake --build _build --target install
    ;;
  osx)
    cmake -H. -B _build -G "Xcode" -DCMAKE_INSTALL_PREFIX=install -DBUILD_TESTS=ON -DBUILD_DOCS=ON
    cmake --build _build --target ALL_BUILD --config Release
    ;;
  windows)
    cmake -H. -B _build -G "Visual Studio 15 2017" -A x64 -DCMAKE_INSTALL_PREFIX=install -DBUILD_TESTS=ON -DBUILD_DOCS=ON
    cmake --build _build --target INSTALL --config Release
    ;;
  esac

# Errors in something run in after_success: don't cause the build to fail so don't use.

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local-dir: install/share/doc/dfdutils/html
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = osx
    #tags: true

# vim:ai:ts=4:sts=2:sw=2:expandtab
